// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfiuhqrvsxrtcikfkglz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5maXVocXJ2c3hydGNpa2ZrZ2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3ODA1NjQsImV4cCI6MjA3NjM1NjU2NH0.9qmNl0om8aiwFkZCENyVqtny-PbXRCoRZ6236wy-INY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});